### PR TITLE
Variable Product Support

### PR DESCRIPTION
**Pull request by Phiph**
Hi @habibillah,
I've been able to implement variable product's into your code without any major changes.

Where possible I've been looking at the type of product to apply any additional logic. It also pulls the variation price, therefor each variation can have its own price. This means in the admin area for variable products does not need to have a quantity field.

Known issues :

- On variation change on product page does not update the drop down.
- Replacement for {price} {total} fields not working. (I'm working on this)

I'll carry on working on these, but just wanted your review on this at the moment! :)

### CODE REVIEW

**Comment by habibillah** [comment]
I have review your code. This does not meet my expectation. A variable product should have each price group for each item. For example, let see this [variable product](http://localhost:8000/shop/ship-your-idea-2/). The **dropdown price** for **black** and **blue** may have difference values. So the admin section should accommodate that requirement.

**Comment by Phiph** [comment]
Hi @habibillah,

I couldn't see your example as it was a localhost link.

At the present each product can have its individual price, just that drop down on the product page isn't updating on changing of variations. 

For example if red was £5 and blue was £6, the code will take the respective percentages off the total price. 

Are you suggesting that for each variation of a product should contain their own quantity breaks & discount?

**Comment by habibillah** [comment]
> I couldn't see your example as it was a localhost link.

Sorry. https://woofix.kalicode.com/shop/ship-your-idea-2/

> Are you suggesting that for each variation of a product should contain their own quantity breaks, discount per variation?

Yep, I think we should have each discount for each variable.

> I don't think that's very user friendly - usually for a set of variable products, the variations would be the options of colour etc,

Yes, that way I'm late to achieve this requirement. Maybe we need tab for each variation. I'm still searching the best way to achieve this feature.

**Comment by Phiph** [comment]
> Sorry. https://woofix.kalicode.com/shop/ship-your-idea-2/

So each variation can have its own price - this works and calculates the discount from the selected variant price.

The price not changing on selection of variation is a known bug, as sated in PR.

> Yep, I think we should have each discount for each variable.

In the project that I extended this code for they have 5 variable products, each having over 500+ variations. Setting a discount per variation would be inefficient for any end user to enter. 

A possibility would be to keep the global product table, where you can set the bulk quantities that you can order, as well as the discount. However a variation can have a overriding discount value. 

This would mean that stores that need to sell variations at a set quantity, can do so, however offer a different discount on a variation for a promotion. 

Let me know what you think.

**Comment by Phiph** [comment]
Added Commit that fixes the variable product dropdown on the product page. 

I've also ensured that scripts load on the pages their needed - not on every page.

**Comment by Phiph** [comment]
Okay - this PR is fully working, and is being used in a production site. There are some performance additions so that the woofix.js only loads in the cart. and the woofix-variations.js loads only for variations.

**Comment by Phiph** [comment]
hi @habibillah, Have you had a chance to review this, and even the performance improvements?

I've noticed you've released 2 updates that would cause conflicts with this PR.

**Comment by Phiph** [comment]
No action from author.

**Pull request closed without merging**
